name: ocr_cicd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  dockerbuild:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Build The Docker Image
        run: docker build -t doc1 .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Check if test PDF exists
        run: |
          if [ ! -f "test/samples" ]; then echo "test/samples not found!"; exit 1; fi


      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run tests
        run: pytest
