name: ocr_cicd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  dockerbuild:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Build The Docker Image
        run: docker build -t doc1 .
      - name: Run the app inside Docker
        run: docker run --name doc1 -d doc1
      - name: docker stop
        run: docker stop -t 10 doc1
      # - name: Wait for the app to be ready
      #   run: sleep 5

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run tests
        run: pytest